CREATE TABLE "POSTOS"(
"ID"     INTEGER not null primary key
         GENERATED ALWAYS AS IDENTITY
         (START WITH 1, INCREMENT BY 1),
"NOME"    VARCHAR(150),

"GASOLINA" DECIMAL(4,2),
"ALCOOL"    DECIMAL(4,2)
);